### ISSUE TITLE
Character shakes when action camera is locked.

### ISSUE THREAD

**Issue by bernek9000** [iZastic/vrising-removevignette#1]
When you lock camera on 3rd person (action camera) the character is somehow lagging a tiny bit behind when camera is rotated horizontally and this causes a shake effect on the character. Not sure if this can be fixed ! Thanks !

**Comment by iZastic** [comment]
RemoveVignette only changes a post processing option and wouldn't be able to cause this.

I think this may have been meant for the ModernCamera mod?

**Comment by iZastic** [comment]
Not an issue with this mod
