### ISSUE TITLE
Extract dll???

### ISSUE THREAD

**Issue by RMorwen** [iZastic/vrising-removevignette#2]
I'd like to install this mod since the vignette effect is driving me crazy, but I can't figure out how to get the dll from your files. I installed visual studio in case it's packed inside one of the other files or needs to be built out of the existing project, but this sort of thing is completely foreign to me and I'm not sure if I'm even getting close to what it is I'm supposed to be doing. Please, how do I "Extract RemoveVignette.dll into (VRising folder)/BepInEx/plugins"??

**Comment by iZastic** [comment]
You can download the mod from https://v-rising.thunderstore.io/package/iZastic/RemoveVignette if you are unable to build it

**Comment by RMorwen** [comment]
Perfect, thank you so much!
